data_loader:
  file_path: "data/synthetic_health.csv"
  file_type: "csv"

transformation:
  normalize: false
  scaling_method: "minmax"


model:
  type: "linear"
  params: {} 

mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "mlops_project_perla_rim_experiments"
