data_loader:
  file_path: "data/sample_data.csv"
  file_type: "csv"
transformation:
  normalize: true
  scaling_method: "standard" # Options: "standard", "minmax"

model:
  type: "linear" # Options: "linear" or "tree